### ISSUE TITLE
Create sitemap

### ISSUE THREAD

**Issue by pieterprovoost** [marco-bolo/dataset-catalogue#18]
Create sitemap of JSON-LD documents for harvesting by OIH.

**Comment by jmckenna** [comment]
@pieterprovoost  feedback on the generated [sitemap](https://raw.githubusercontent.com/marco-bolo/dataset-catalogue/main/datasets/sitemap.xml) & its [script](https://github.com/marco-bolo/dataset-catalogue/blob/main/scripts/publish_test_output.py) :
- the sitemap is invalid because it lacks the proper 2 header lines:
  - taken from a similar sitemap [script](https://github.com/iodepo/odis-arch/blob/master/collection/scripts/wio-symphony-sitemap.py#L51)
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9/">
      ...
    </urlset>
    ```

**Comment by pieterprovoost** [comment]
@jmckenna Should be ok now.

**Comment by pieterprovoost** [comment]
@jmckenna Just realized that I already have a [sitemap generated as part of the validation report](https://lab.marcobolo-project.eu/dataset-catalogue/sitemap.xml), I updated ODISCat.
